version: 2

sources:
  - name: pharma
    database: PHARMA_DB
    schema: P_RAW_SCH  # Raw data schema
    tables:
      - name: DOCTORS
      - name: DRUGS
      - name: INVENTORY
      - name: MANUFACTURERS
      - name: PATIENTS
      - name: PHARMACIES
      - name: PRESCRIPTIONS
      - name: PRESCRIPTION_ITEMS

models:
  - name: doctors_tb
    description: "Transformed doctor data with standardized names, phones, and license info."
    columns:
      - name: doctor_id
        description: "Unique ID of the doctor"
        tests:
          - unique
          - not_null

      - name: first_name
        description: "First name parsed from full name"

      - name: last_name
        description: "Last name parsed from full name"

      - name: specialization
        description: "Doctor's medical specialty"

      - name: hospital
        description: "Hospital the doctor is affiliated with"

      - name: phone_digits
        description: "Digits-only version of phone number"

      - name: email
        description: "Lowercased email address"

      - name: license_number
        description: "Full license ID"

      - name: license_state
        description: "State extracted from license number"

  - name: drugs_tb
    description: "Enriched drug data with standardized formatting, expiry logic, and calculated fields."
    columns:
      - name: drug_id
        description: "Unique ID for the drug"
        tests:
          - unique
          - not_null

      - name: brand_name
        description: "Capitalized brand name for display purposes"

      - name: generic_name
        description: "Capitalized generic name for standardization"

      - name: dosage_form
        description: "Lowercased form of drug (e.g. tablet, injection)"

      - name: drug_category
        description: "Normalized category of the drug"

      - name: manufacturer_id
        description: "Manufacturer reference ID"

      - name: price_usd
        description: "Rounded retail price in USD"

      - name: storage_conditions
        description: "Lowercased storage instructions (e.g. frozen)"

      - name: expiry_months
        description: "Shelf life in months"

      - name: expiry_classification
        description: "Classified shelf life: Short-Term, Medium-Term, Long-Term"

      - name: estimated_expiry_date
        description: "Calculated expiry date based on shelf life"

      - name: value_lifetime
        description: "Total price value over product shelf life"

  - name: inventory_tb
    description: "Transformed inventory data with standardized dates, stock status, and shelf life calculations."
    columns:
      - name: inventory_id
        description: "Unique identifier for the inventory record"
        tests:
          - not_null
          
      - name: pharmacy_id
        description: "Pharmacy identifier where the drug is stored"
        
      - name: drug_id
        description: "ID of the drug associated with this inventory item"
        
      - name: quantity
        description: "The number of units available in stock"
        tests:
          - not_null
          
      - name: batch_number
        description: "The batch number assigned to the inventory item"
        
      - name: manufacture_date
        description: "Date the drug was manufactured (standardized to YYYY-MM-DD)"
        
      - name: expiry_date
        description: "Date the drug expires (standardized to YYYY-MM-DD)"
        
      - name: last_restocked
        description: "The last date the inventory was restocked (standardized to YYYY-MM-DD)"
        
      - name: shelf_life_days
        description: "Shelf life of the drug in days (calculated from manufacture to expiry)"
        
      - name: days_since_restock
        description: "Days since the last restock of this item"
        
      - name: inventory_status
        description: "Status of the inventory: 'Expired' or 'Active'"
        
      - name: stock_status
        description: "Categorization of the inventory stock level: 'Out of Stock', 'Low Stock', or 'In Stock'"

  - name: manufacturer_tb
    description: "Transformed manufacturer data with standardized names, years in business, and clean contact info."
    columns:
      - name: manufacturer_id
        description: "Unique identifier for the manufacturer"
        tests:
          - unique
          - not_null
          
      - name: manufacturer_name
        description: "Standardized name of the manufacturer"
        
      - name: address
        description: "Address of the manufacturer"
        
      - name: country
        description: "Country where the manufacturer is based (lowercased)"
        
      - name: contact_person
        description: "Contact person for the manufacturer (capitalized)"
        
      - name: email
        description: "Normalized email address (lowercased)"
        
      - name: phone_digits
        description: "Phone number with non-numeric characters removed"
        
      - name: established_year
        description: "Year the manufacturer was established"
        
      - name: years_in_business
        description: "The number of years the manufacturer has been in business"
        
      - name: manufacturer_age_category
        description: "Category based on how long the manufacturer has been in business ('Long Established' or 'Newer')"

  - name: patients_tb
    description: "Transformed patient data with standardized fields, age group categorization, and data quality flags."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient."
        tests:
          - unique
          - not_null

      - name: patient_name
        description: "Formatted name of the patient with proper capitalization."

      - name: date_of_birth
        description: "Patient's date of birth in standardized YYYY-MM-DD format."

      - name: gender
        description: "Lowercased gender value for consistency (e.g., 'm', 'f')."

      - name: blood_type
        description: "Normalized blood type (e.g., 'o+', 'a-') in lowercase."

      - name: address
        description: "Residential address of the patient."

      - name: phone_digits
        description: "Cleaned patient phone number containing only numeric digits."

      - name: email
        description: "Lowercased email address of the patient."

      - name: emergency_contact
        description: "Name of the emergency contact person."

      - name: emergency_phone_digits
        description: "Cleaned emergency contact phone number with only digits."

      - name: age
        description: "Calculated age of the patient based on the date of birth."

      - name: age_group
        description: "Age category: 'Pediatric' (≤18), 'Adult' (19–64), or 'Senior' (≥65)."

      - name: contact_info_status
        description: "Flag indicating missing phone or email: 'Missing Phone', 'Missing Email', or 'Valid Contact Info'."

      - name: address_status
        description: "Flag indicating whether the address is valid or missing."

      - name: birth_month
        description: "Numerical month (1–12) extracted from the date of birth."

      - name: patient_status
        description: "Overall status of the patient: 'Active' if they have phone, email, and emergency contact; otherwise 'Inactive'."  

  - name: pharmacies_tb
    description: "Standardized pharmacy data with contact validation, region mapping, and license parsing."
    columns:
      - name: pharmacy_id
        description: "Not NULL of the pharmacy"
        tests:
          - not_null

      - name: pharmacy_name
        description: "Capitalized name of the pharmacy"

      - name: address
        description: "Street address"

      - name: city
        description: "City where the pharmacy is located"

      - name: state
        description: "State name"

      - name: zip_code
        description: "ZIP code formatted as 5-digit text"

      - name: full_location
        description: "Concatenation of city, state, and ZIP code"

      - name: phone_digits
        description: "Phone number stripped of special characters"

      - name: phone_status
        description: "Status of the phone number (valid, missing, invalid)"

      - name: email
        description: "Lowercased pharmacy email"

      - name: email_domain
        description: "Domain extracted from email"

      - name: email_status
        description: "Status of the email field (valid, missing, invalid)"

      - name: license_number
        description: "Full pharmacy license"

      - name: license_prefix
        description: "License prefix (e.g., PH)"

      - name: license_suffix
        description: "License suffix (e.g., DPKE)"

      - name: license_status
        description: "Indicates if the license number exists"

      - name: business_region
        description: "Region classification based on state"

      - name: name_length
        description: "Length of the pharmacy name"

      - name: name_length_status
        description: "Flags overly long or short pharmacy names"

  - name: prescription_items_tb
    description: "Enhanced prescription items with dosage breakdowns and total expected medication calculations."
    columns:
      - name: item_id
        description: "Unique identifier for each prescription item"
        tests:
          - unique
          - not_null

      - name: prescription_id
        description: "ID referencing the prescription"

      - name: drug_id
        description: "ID referencing the prescribed drug"

      - name: quantity
        description: "Quantity prescribed for the item"

      - name: dosage
        description: "Original dosage text (e.g., '1 ml')"

      - name: dosage_amount
        description: "Numeric value extracted from the dosage field"

      - name: frequency
        description: "Frequency of dosage (e.g., 'Twice daily')"

      - name: daily_dosage_count
        description: "Numeric representation of frequency (e.g., 2 for 'twice daily')"

      - name: duration_days
        description: "Number of days the prescription is to be taken"

      - name: total_doses_expected
        description: "Expected total number of doses over the duration"

      - name: total_volume_expected
        description: "Expected total volume of medication consumed (e.g., in ml)"

  - name: prescriptions_tb
    description: "Transformed prescriptions data with validity logic, duration, and status normalization."
    columns:
      - name: prescription_id
        description: "Unique prescription identifier"
        tests:
          - not_null

      - name: patient_id
        description: "ID of the patient associated with this prescription"

      - name: doctor_id
        description: "ID of the doctor who issued the prescription"

      - name: issue_date
        description: "Standardized prescription issue date"

      - name: expiry_date
        description: "Standardized prescription expiry date"

      - name: status_normalized
        description: "Normalized lowercase version of the prescription status (e.g., active, expired)"

      - name: prescription_duration_days
        description: "Total number of days the prescription is valid for"

      - name: days_to_expiry
        description: "Number of days remaining until expiry (negative if already expired)"

      - name: prescription_validity
        description: "Flag indicating if the prescription is currently valid, expired, or upcoming"

      - name: date_quality_flag
        description: "Validation flag for checking missing or inconsistent dates"

